name: Deploy Website

on:
  push:
    branches:
      - main  # Deploy when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-username/portfolio-website:latest .
        docker push your-dockerhub-username/portfolio-website:latest

    - name: Deploy Docker Compose
      run: |
        docker-compose up -d
